FROM node 
# node is the base container/base image.

CMD ["node","-e","console.log('Container Execution Started')"]
# node -e -> It actually helps u to execute a valid NodeJS statement without actually opening the NodeJS repl console or without actually creating a JS file.
#  CMD instruction is used to provide default commands or parameters for the container when it starts. It specifies the command that will be executed by default when a container is run from the built image. eg. CMD ["echo", "Hello, Docker!"].